# install_headers_smoke.cmake
# CR-084 配套冒烟：安装构建树到临时 prefix，然后编译一个包含"安装树全部头文件"
# 的探针 TU。防止 install 规则遗漏依赖闭包（曾遗漏 util/exception_handler.hpp
# 导致下游包含 cuda_executor.hpp 编译失败）。
#
# ctest 调用方式（见 tests/CMakeLists.txt）：
#   cmake -DBUILD_DIR=<build> -DCXX_COMPILER=<cc> -P install_headers_smoke.cmake
#
# 限制：探针编译用 CXX_COMPILER 直接驱动（GNU/Clang 语法），MSVC 未覆盖
# （注册处按编译器过滤）。

set(prefix "${BUILD_DIR}/install_smoke_prefix")
file(REMOVE_RECURSE "${prefix}")

execute_process(
    COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --prefix "${prefix}"
    RESULT_VARIABLE install_result
    OUTPUT_VARIABLE install_output
    ERROR_VARIABLE install_error
)
if(NOT install_result EQUAL 0)
    message(FATAL_ERROR "cmake --install failed:\n${install_output}\n${install_error}")
endif()

file(GLOB_RECURSE installed_headers
    LIST_DIRECTORIES FALSE
    "${prefix}/include/*.hpp"
    "${prefix}/include/*.h"
)
list(LENGTH installed_headers header_count)
if(header_count EQUAL 0)
    message(FATAL_ERROR "no headers found under ${prefix}/include — install rules broken")
endif()
list(SORT installed_headers)

set(probe "${BUILD_DIR}/install_smoke_probe.cpp")
file(WRITE "${probe}" "// Generated by install_headers_smoke.cmake — includes every installed header.\n")
foreach(header IN LISTS installed_headers)
    file(APPEND "${probe}" "#include \"${header}\"\n")
endforeach()
file(APPEND "${probe}" "\nint main() { return 0; }\n")

execute_process(
    # 消费者契约：-I<prefix>/include 后 #include <kairo/...> 可用
    COMMAND "${CXX_COMPILER}" -std=c++20 -fsyntax-only
            "-I${prefix}/include" "${probe}"
    RESULT_VARIABLE compile_result
    OUTPUT_VARIABLE compile_output
    ERROR_VARIABLE compile_error
)
if(NOT compile_result EQUAL 0)
    message(FATAL_ERROR
        "probe TU including all ${header_count} installed headers failed to compile:\n"
        "${compile_output}\n${compile_error}")
endif()

message(STATUS "install_headers_smoke: ${header_count} installed headers compile OK")
